build.sbt
smrt-server-tools/build.sbt
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/client/ServiceAccessLayer.scala
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/tools/GetStatus.scala

This builds and get-status is runnable, but it exits with code 1 and I can't figure out why.

started smrt-server-tools project, with initial ServiceAccessLayer API and get-status replacement

---

build.sbt
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/PbDataSetTools.scala
smrt-server-base/build.sbt

Mark all tests to not run in parallel.

Slightly improve PbDataSet tool. Still WIP.

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/engine/EngineDao.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/jobs/JobModels.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/jobs/SecondaryJsonProtocols.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/ImportDataStoreServiceType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/ImportFastaServiceType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/PbsmrtpipeServiceJobType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/RsConvertMovieToDataSetServiceType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/SimpleServiceJobType.scala
smrt-server-analysis/src/test/scala/JobExecutorSpec.scala
smrt-server-analysis/src/test/scala/JobManagerServiceSpec.scala
smrt-server-analysis/src/test/scala/SecondaryJobSpec.scala
smrt-server-base/src/main/scala/com/pacbio/common/auth/ApiUser.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDaoActor.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/database/TableModels.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/Models.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/SmrtLinkJsonProtocols.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobManagerService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/ProjectService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/jobtypes/ImportDataSetServiceType.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/jobtypes/MergeDataSetServiceType.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/jobtypes/MockPbsmrtpipeJobType.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/tools/SetupMockData.scala
smrt-server-link/src/main/scala/db/migration/V8__JobUser.scala
smrt-server-link/src/test/scala/JobExecutorSpec.scala

have job endpoints record and respond with the user that created the job, for jobs created by logged-in users

bug 31728: add and populate createdBy field for jobs

---

.gitignore
smrt-server-tools/build.sbt
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/client/ServiceAccessLayer.scala
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/tools/PbService.scala

more service endpoints and pbservice prototype

---

smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/client/ServiceAccessLayer.scala
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/tools/PbService.scala

add job polling to dataset import

---

smrt-server-tools/src/main/resources/application.conf
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/client/ServiceAccessLayer.scala
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/tools/GetStatus.scala
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/tools/PbService.scala

This now should be nearly ready to replace the old 'get-status' Python script.

fix status check connection error, and add endpoint checks

---

smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/client/ServiceAccessLayer.scala
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/tools/PbService.scala

All of the commands in the Python version have at least a stub working now, and I can successfully start a job on smrtlink.

more commands in pbservice

---

build.sbt
smrt-server-analysis-internal/build.sbt
smrt-server-analysis-internal/src/main/resources/application.conf
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/Constants.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/InternalAnalysisJsonProcotols.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/JobResolvers.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/RunCodeUtils.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/SecondaryInternalAnalysis.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/daos/LimsDao.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/daos/ReferenceResourceDao.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/daos/SmrtLinkResourceDao.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/models/Models.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/services/LimsResolverService.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/services/ReferenceSetResolverService.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/services/SmrtLinkResourceService.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/tempbase/package.scala
smrt-server-analysis-internal/src/main/webapp/WEB-INF/web.xml
smrt-server-analysis-internal/src/test/scala/JobResolverSpec.scala
smrt-server-analysis-internal/src/test/scala/RuncodeResolverSpec.scala
smrt-server-analysis-internal/src/test/scala/SanitySpec.scala

This needs another pass to remove RS-era POCs.

Added internal analysis smrt-server.

---

smrt-server-logging/Readme.md

CC @skinner @mpkocher 
A few commits didn't make it in before #42 was merged. I also would like to merge #44 to the branch before `master` so that the tool refactoring goes in.
I'll keep this up for some feedback then merge.

Logging improvements (Again)

---

smrt-server-base/build.sbt
smrt-server-base/src/main/scala/com/pacbio/common/client/ServiceAccessLayer.scala
smrt-server-base/src/main/scala/com/pacbio/common/tools/GetStatus.scala
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/client/ServiceAccessLayer.scala
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/tools/GetStatus.scala

Here's the minimal implementation.  I could do the equivalent for 'pbservice' with only the 'status' command, but I'd like to understand how to extend these classes first.

abstracted out core services client functionality

---

build.sbt
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/CommandLineUtils.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/DataSetMergerTool.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/FastaToReference.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/FastaToReferenceDataSet.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/ImportDataSet.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/MovieMetaDataToDataSet.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/MovieMetaDataToDataSetRtc.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/ReferenceInfoToDataSet.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/ValidateDataSet.scala
smrt-analysis/src/test/scala/DataSetMergerSpec.scala
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/tools/PbService.scala

Replaces #44. Same code but merge target `master` not the old logging branch.
If the tests pass, I'll get this merged.

Services with logging (Merge to `master`)

---

smrt-server-analysis-internal/README.md
smrt-server-analysis/README.md
smrt-server-base/README.md
smrt-server-link/README.md
smrt-server-tools/README.md

The rest of the docs. Fixes #54 and follow-up to #83

More terse docs

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/converters/FastaToReferenceConverter.scala

check for output dir and exit with error if it already exists

---

smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala

Fix job updated at when state is changed.

---

smrt-server-base/src/main/scala/com/pacbio/common/services/package.scala

This is to try and get more context about the errors we've been seeing on beta

log http requests, log backtrace if throwable message is null

---

build.sbt
smrt-server-analysis/build.sbt
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/TestkitRunner.scala

This will run a job, but it doesn't pass any options yet (or check results).

starting port of pbtestkit-service-runner

---

.gitignore
makefile

stress test that imports many datasets

---

style_guide.md

One last commit that didn't make in pre-merge #116

Example of ignoring SQL in migrations

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/reports/Reports.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/client/ServiceAccessLayer.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/TestkitRunner.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/client/ServiceAccessLayer.scala

automatic testing of analysis job report attributes

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/pipelines/PipelineTemplatePresetLoader.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/reports/Reports.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/TestkitRunner.scala

With pbsmrtpipe-like syntax.  I had to modify the preset loader to get this to work.

added `pbservice run-pipeline` command

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala

Which doesn't do as much as I thought it would, unfortunately.

add (partial) fasta validation before import

---

build.sbt
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/reports/Reports.scala
smrt-analysis/src/test/scala/ReportsSpec.scala
smrt-common-models/src/main/scala/com/pacbio/common/models/JsonProtocols.scala
smrt-server-base/src/main/scala/com/pacbio/common/models/JsonProtocols.scala

I'm not very confident about the UUID-serialization refactoring - this was the only way I could think of to avoid circular dependencies.

Report update

---

.gitignore
REQUIREMENTS.txt
makefile
stress.py
test-data/runCreate2.xml

It may be a bit of a hack in the sense that it doesn't use pbservice.  But AFAICT pbservice doesn't do run designs, so this seemed like a reasonable approach.

add run designs in stress test

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/TestkitRunner.scala

plus a possible fix for hanging on uncaught exception, and some refactoring for better return code handling

added xunit output to new testkit runner

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/reports/Reports.scala
smrt-analysis/src/test/scala/ReportsSpec.scala

@mpkocher does this address most of our remaining issues or am I missing some details still?

add table columns to Report model, with support for mixed element types

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala

This was present in the Python implementation.

add --debug option to pbservice

---

smrt-server-base/src/main/scala/com/pacbio/common/app/BaseSmrtServerApp.scala
smrt-server-logging/src/main/scala/com/pacbio/logging/LoggerConfig.scala

Found some unneeded semicolons in our code. Good-bye!

Useless semicolons

---

smrt-server-database/src/main/scala/com/pacbio/database/Database.scala

A few quick updates to expose Slick use that appears to be fundamentally incompatible with SQLite. Two bad assumptions are fixed here:
1. DB use wouldn't hard timeout. It now will after 10s
2. Sharing the `Connection` instance is now limited back to just Flyway migrations. It lead to cases where an SQL transaction could attempt to be created in an existing transaction, which locks up SQLite.
One thing that appeared to lock up an `Actor` was use of Slick's `.transactionally`. I'm still sorting out if we're limited to not using this at all or just being aware that it can potentially be an issue.

Exposes `.transactionally` and other incompatible DB use bugs

---

circle.yml

add PacBioTestData repo to CircleCI tests

---

smrt-server-logging/README.md
smrt-server-logging/src/main/scala/com/pacbio/logging/LoggerConfig.scala
smrt-server-logging/src/main/scala/com/pacbio/logging/LoggerOptions.scala
smrt-server-logging/src/test/scala/com/pacbio/logging/LoggerSpec.scala

Some doc updates and a test case that covers most expected use cases. See #186. It was merged before I could get this pushed to origin/master.
I'll merge as soon as CircleCI says green.

Docs + Test for logging updates in #186

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala

add --non-local import for import-dataset command

---

smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/tools/SetupMockData.scala

It's runnable via 
sbt "smrt-server-link/run-main com.pacbio.secondary.smrtlink.tools.InsertMockData"

Add mock importing of data tool.

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/jobs/JobExecutor.scala

@jfalkner @mpkocher
With this change, I no longer see import failures with stress.py.  I still see stress.py failures occasionally on analysis jobs, but the failure rate went from 2-6 failures per run to one failure every few runs.
I started with a smaller change that just `map`ped the futures from `ImportDataStoreFile` into the future returned by `importDataStore`.  But that resulted in a ClassCastException.  It turned out that the `.mapTo[Either[FailedMessage, SuccessMessage]]` in `importDataStoreFile` wasn't right.  I imagine the type of the `ImportDataStoreFile` message response changed at some point, but the importDataStore code wasn't updated.
So I did a slightly larger refactoring to get the types to line up.  And I dropped the onSuccess and onFailure callbacks, which were only …

have JobExecutor wait for imports to finish

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/converters/FastaToBarcodeSetConverter.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/jobtypes/ConvertImportFastaBarcodesJob.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/appcomponents/SecondaryAnalysisApp.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/client/ServiceAccessLayer.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/ImportBarcodeFastaServiceType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/client/ServiceAccessLayer.scala

Example usage:
```
pbservice import-barcodes barcodes.fasta my_barcodes --host localhost --port 8070
```

new job type and endpoint: import FASTA as BarcodeSet

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/engine/actors/EngineManagerActor.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobManagerService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobsBaseMicroService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/SmrtLinkBaseMicroService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/jobtypes/ValidateImportDataSetUtils.scala

I made these changes on the S3.1 branch but hadn't propagated them to git until now.  This is a subset of
http://swarm/changes/182032
that applies to the current git master.

bump timeouts and remove redundant running state transition

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/pbsmrtpipe/PbsmrtpipeConstants.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/loaders/EnvResourceLoader.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/loaders/JsonAndEnvResourceLoader.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/loaders/JsonResourceLoader.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/loaders/PipelineTemplateResourceLoader.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/loaders/PipelineTemplateViewRulesResourceLoader.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/loaders/ReportViewRulesResourceLoader.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/loaders/ResourceLoaderBase.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/ReportViewRulesService.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/ResolvedPipelineTemplateService.scala

- resolved-pipeline-templates
- pipeline-template-view-rules
- report-view-rules
Added env vars
- PB_RULES_PIPELINE_VIEW_DIR
- PB_RULES_REPORT_VIEW_DIR

Add loading of resources from ENV

---

makefile
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/CommandLineUtils.scala
smrt-server-analysis/build.sbt
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/DatabaseTool.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/tools/SetupMockData.scala

There's still some friction over smrt-server-link and smrt-server-analysis DB URI.
For common  CLI interface, added explicit sys.exit call.

Add db summary tool

---

smrt-server-link/src/main/resources/application.conf
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/tools/SetupMockData.scala

and use db-native counting for the system summary

make mock db rowcounts a little more like beta

---

makefile
stress.py

use beta DB copy in stress test; use subreadset that pbreports succeeds on

Stress test loose ends

---

smrt-server-lims/README.md
smrt-server-lims/scripts/find_and_load_recent_lims_yml.sh
smrt-server-lims/src/production_deploy.md

Added some docs and a copy of a script used to sync recent lims.yml files to the server hourly.

hourly update and prod deploy docs

---

makefile
setup-tools-env.sh
smrt-server-analysis-internal/build.sbt
smrt-server-analysis-internal/src/main/resources/application.conf
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/JobResolvers.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/SecondaryInternalAnalysis.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/SmrtLinkAnalysisInternalConfig.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/client/InternalAnalysisServiceClient.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/models/Models.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/services/jobtypes/ConditionJobType.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/tools/InternalAnalysisClientToolApp.scala
smrt-server-base/src/main/scala/com/pacbio/common/client/ServiceAccessLayer.scala

Still WIP, CLI submit doesn't work yet.

Add SLIA Client and CLI tool

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/testkit/JobRunner.scala

check for consistency of report UUIDs and datastore

---

build.sbt

This is a first pass to get the mechanics to work successfully.

Write pacbio-manifest.json as a managed resource

---

extras/run_sim_local.py
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/client/ServiceAccessLayer.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/testkit/JobRunner.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDaoActor.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/client/ClientUtils.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/client/ServiceAccessLayer.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/database/TableModels.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/Converters.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/Models.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/SmrtLinkJsonProtocols.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/DataSetService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobService.scala
smrt-server-link/src/test/scala/DatabaseSpec.scala
smrt-server-sim/src/main/scala/com/pacbio/simulator/scenarios/DataSetImportScenario.scala
smrt-server-sim/src/main/scala/com/pacbio/simulator/steps/SmrtAnalysisSteps.scala
smrt-server-sim/src/main/scala/com/pacbio/simulator/steps/SmrtLinkSteps.scala

@mpkocher and @smcclellan7 you should probably review this

dataset import tests

---

smrt-common-models/src/main/scala/com/pacbio/common/models/Models.scala
smrt-common-models/src/test/scala/ModelsSpec.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/DataSetService.scala

Add IdAble model to start to replace Either[Int, UUID]

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/pbsmrtpipe/IOUtils.scala
smrt-analysis/src/test/scala/PbsmrtpipeEngineOptionsSpec.scala

The test case is kind of overkill - I was mostly using for debugging - but I think this kind of cycling is valuable to have anyway.

special handling for empty string in preset xml output

---

build.sbt
makefile
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/engine/EngineDao.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/jobs/JobModels.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/services/jobtypes/ConditionJobType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/DirectPbsmrtpipeJobType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/ImportBarcodeFastaServiceType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/ImportDataStoreServiceType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/ImportFastaServiceType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/PbsmrtpipeServiceJobType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/RsConvertMovieToDataSetServiceType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/SimpleServiceJobType.scala
smrt-server-base/src/main/scala/com/pacbio/common/loaders/ManifestLoader.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDaoActor.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/app/SmrtLinkConfigProvider.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/jobtypes/ImportDataSetServiceType.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/jobtypes/MergeDataSetServiceType.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/jobtypes/MockPbsmrtpipeJobType.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/tools/SetupMockData.scala
smrt-server-link/src/test/scala/DatabaseSpec.scala

There's quite a few options passed to the job types. This could benefit from a new data model.

Load SL and SL-tools version from pacbio-manifest.json

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/engine/EngineDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDaoActor.scala

fixes bug where excess jobs got stuck in CREATED state

better handling of quick vs. regular jobs

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala

@mpkocher this look right to you?

match RSII movie name format when finding metadata files recursively

---

smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/client/InternalAnalysisServiceClient.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/client/ServiceAccessLayer.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/client/ClientUtils.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/client/ServiceAccessLayer.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/Models.scala
smrt-server-sim/src/main/scala/com/pacbio/simulator/scenarios/ProjectsScenario.scala
smrt-server-sim/src/main/scala/com/pacbio/simulator/steps/SmrtLinkSteps.scala

@mpkocher @skinner any thoughts?  it's messy but it works (minus authentication of course).  I thought about making it possible to set a project for datasets generated by other job types but this will increase the complexity considerably and I'm not sure how useful it is.

start adding projects support to pbservice

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/constants/FileTypes.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala

Cleaning up some code duplication too.

support project assignment for reference and barcode imports

---

extras/test_pbservice_imports.sh
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/converters/PacBioFastaValidator.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/client/ServiceAccessLayer.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/client/ClientUtils.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/client/ServiceAccessLayer.scala

This gets rid of most of the code duplication in the XML and FASTA import functions.

pbservice refactoring

---

extras/wso2/create_roles.sh
extras/wso2/smrtlink_swagger.json

- Change PbBioinformatics role to PbBioinformatician
- Add run-qc scope to PbBioinformatician role

Swagger Changes

---

extras/wso2/smrtlink_swagger.json

These changes make the swagger file valid.
Using node_modules/swagger-cli/bin/swagger.js validate /path/to/swagger.json
Can be installed npm install swagger-cli

Add info to root level and add description to all response 

---

extras/pbbundler/fabfile.py
extras/pbbundler/jenkins_build_smrtflow.sh

@mpkocher I can now build this locally, I think it'll require a few minor tweaks to Jenkins to make it work there.

make pbbundler easier to run outside of jenkins job

---

build.sbt
smrt-server-link/src/main/scala/db/migration/V19__JobDelete.scala
smrt-server-sim/src/main/scala/com/pacbio/simulator/scenarios/DataSetScenario.scala
smrt-server-sim/src/main/scala/com/pacbio/simulator/scenarios/PbsmrtpipeScenario.scala
smrtlink_swagger.json

@mpkocher is there anything else I need to include in these tests before I declare the issue closed?

more delete-job tests, including pbsmrtpipe job and failure mode

---

build.sbt
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDaoActor.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/app/SmrtLinkApp.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/database/TableModels.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/Models.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/SmrtLinkJsonProtocols.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/EulaService.scala
smrt-server-link/src/main/scala/db/migration/V21__EulaRecord.scala
smrtlink_swagger.json

@mpkocher please review, this is just the database layer but I would like to confirm that this is an appropriate approach before I pile too much on top

backend support for EULAs

---

smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/database/TableModels.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/Models.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/SmrtLinkJsonProtocols.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/ProjectService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/tools/SetupMockData.scala
smrt-server-link/src/test/scala/DatabaseSpec.scala
smrt-server-link/src/test/scala/ProjectSpec.scala

- Validate project state. (Either "CREATED" or "ACTIVE")
- Reject updates that remove all owners from a project.

Project Validation

---

smrt-server-base/src/main/scala/com/pacbio/common/services/AbstractFilesService.scala
smrt-server-base/src/test/scala/FilesServiceSpec.scala

@mpkocher pretty sure i did this right but someone should double-check that there won't be side effects

handle spaces in path correctly in files service

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/AmClient.scala

Apparently 200 seconds isn't long enough to wait for API manager to start up?
http://jenkins:8080/view/smrtlink/job/smrtlink-bihourly/4917/consoleFull

bump timeouts

---

build.sbt
circle.yml
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/constants/FileTypes.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/datasets/DataSetModels.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/jobtypes/DeleteResourcesJob.scala
smrt-analysis/src/test/scala/DeleteResourcesSpec.scala
smrt-server-analysis/src/main/resources/smrtlink_swagger.json
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/appcomponents/SecondaryAnalysisApp.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/client/ServiceAccessLayer.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/models/SecondaryAnalysisJsonProtocols.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/models/SecondaryModels.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/DeleteDataSetsServiceType.scala
smrt-server-sim/src/main/scala/com/pacbio/simulator/scenarios/DataSetScenario.scala
smrt-server-sim/src/main/scala/com/pacbio/simulator/steps/SmrtAnalysisSteps.scala

Including deleting entry points for an auto-merged dataset - I'm not sure if we really need to handle the recursive case.

Delete dataset service

---

smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/jobtypes/MockPbsmrtpipeJobType.scala
smrt-server-link/src/test/scala/JobExecutorSpec.scala

WIP: Fix JobExecutorSpec

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/jobs/CoreJob.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/package.scala
smrt-server-logging/src/main/scala/com/pacbio/logging/LoggerConfig.scala

Changing the logging of HTTP requests to only display the method, URI, and content (if any).

logging cleanup

---

extras/pbbundler/smrtlink_services_ui/bin/start

[SL-637] set heap size for API manager client

---

makefile
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/jobs/JobExecutor.scala
smrt-server-analysis/src/main/resources/application.conf
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/client/ServiceAccessLayer.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala
smrt-server-database/src/main/scala/com/pacbio/database/Database.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/EulaService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobManagerService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobsBaseMicroService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/SmrtLinkBaseMicroService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/jobtypes/ValidateImportDataSetUtils.scala

Master branch version of PR #423

Runnablejob race and bump timeouts (master branch)

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/ImportFastaServiceType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala

Also removing the file size cap in `pbservice`.

fix FASTA import/pbsmrtpipe cluster settings bug

---

extras/pbbundler/bamboo_build.sh

@mpkocher this won't interfere with your ongoing postgres-related work, will it?

display both smrtflow and UI SHAs in tarball

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/client/ClientUtils.scala

I had a specific reason for doing this which I've now forgotten.  Totally non-essential, anyway.

add option to display report attributes in 'pbservice get-job'

---

smrt-server-base/src/main/scala/com/pacbio/common/services/utils/FutureSecurityDirectives.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/ProjectService.scala
smrt-server-link/src/test/scala/ProjectSpec.scala

Should this be going into the postgres branch instead of master?  It should be pretty orthogonal to that work, so hopefully it merges relatively cleanly either way.  So let me know if I should rebase and re-point it to a different branch.

SL-711 limit project operations by membership role

---

extras/pbbundler/smrtlink_services_ui/bin/apply-config

fix apply-config bug

---

extras/pbbundler/smrtlink_services_ui/bin/start

We don't really need to wait for tests on this, do we?

another bug fix

---

smrt-server-analysis/src/main/resources/smrtlink_swagger.json

updates:
/secondary-analysis/pipeline-template-view-rules
in swagger json. and contains minor formatting fix.

add PipelineTemplateViewRules defintion to smrtlink_swagger.json

---

extras/pbbundler/smrtlink_services_ui/bin/stop
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/DatabaseTool.scala

Plus bonus bug fix to services shutdown script.

refactor database tool

---

smrt-server-analysis/src/main/resources/smrtlink_swagger.json

updates to:
/secondary-analysis/dataset-types
/services/manifests
/smrt-link/runs
/smrt-link/runs/{runID}/collections/{collection ID}

update endpoint definitions in smrtlink swagger

---

build.sbt

This should have been done in b2668ed7df45d43a1eba82d73e44eddfbe5d9c77

Bump version to 0.4.1 for added automation-constraint service
