PacificBiosciences/smrtflow

smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/client/ServiceAccessLayer.scala
smrt-server-tools/src/main/scala/com/pacbio/secondary/smrttools/tools/PbService.scala

The reference name is non-optional in this implementation; we really shouldn't have blank reference names in smrtlink.

add import-fasta command

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/jobs/JobModels.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/jobs/SecondaryJsonProtocols.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/DirectPbsmrtpipeJobType.scala

[Bug 33059] Added pbsmrtpipe "direct" job type by pass resolving of DataSet to Path.
- This is intended for internal testing and for pipelines that don't all have entry-points that are DataSet types.
- Want to get internal analysis pipelines running that have Condition JSON files types as inputs
- Need to do some refactoring to reduce the duplication.

Add Direct/Raw pbsmrtpipe job type

---

build.sbt

Fixes #49 and #50 by adding the `smrt-server-logging` JAR to classpath, which means the default `Configurator` will be used.
Much less verbose test output.

Logging JAR now in all projects

---

smrt-server-base/src/main/resources/application.conf

@skinner @natechols @mpkocher 
Title says it all. Now you won't see those 3 unhelpful lines every time this one `application.conf` is loaded.
```bash
[DEBUG] [05/17/2016 12:26:58.398] [pool-1-thread-1] [EventStream] StandardOutLogger started
[DEBUG] [05/17/2016 12:26:58.759] [pool-1-thread-1] [EventStream(akka://SecondaryJobSpec)] logger log1-Slf4jLogger started
[DEBUG] [05/17/2016 12:26:58.760] [pool-1-thread-1] [EventStream(akka://SecondaryJobSpec)] Default Loggers started
```
I'm not aware of any helpful information coming from this logger. We could probably delete the line entirely.

Remove unhelpful initial Akka stdout logging

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/appcomponents/SecondaryAnalysisApp.scala
smrt-server-base/src/main/scala/com/pacbio/common/app/BaseSmrtServerApp.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/app/SmrtLinkApp.scala
smrt-server-logging/src/main/scala/com/pacbio/logging/LoggerOptions.scala

@skinner @mpkocher 
Fixes #55
Adds command-line argument parsing for logging to the servers noted here https://github.com/PacificBiosciences/smrtflow/issues/55#issuecomment-219824672
The server code didn't use `scopt`; however, it is an `App` entry point that has CLI args. I added a util method so that if logging options are passed to the command line, they'll be used. This means that command line `--logfile` and `--loglevel` flags can now be used instead of a `logback.xml` file plus a properties file to config the log file and log level.
e.g.
```bash
java -jar target/scala-2.11/smrt-server-analysis*.jar --logfile /tmp/my_file.log --loglevel ERROR
```
And `-h` still works.
```
Usage: ./app_with_logging [options]
This is an app that supports PacBio logging flags. 
-h | --help
Show Options …
```

SecondaryAnalysisApp CLI logging arg support

---

smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala

Fixes #58 
I'm not sure if this is the ideal long-term fix, but it makes the code work as expected when running the code as noted in #58. The problematic case was if you lacked a `db` directory. Without manually making it, the code would error and exit.

Lazy make needed  `db` dir

---

smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/services/jobtypes/ConditionJobType.scala

- This will enable the pipeline id to be displayed in the UI
- Dealing with the entry points still needs to be addressed

Add Condition job options to jsonSettings

---

smrt-server-logging/src/main/scala/com/pacbio/logging/LoggerConfig.scala

Fixes #70
Nothing fancy. Removed some sold hard-coded logger name cruft and changed the tooling to only add the appender to the ROOT logger.

One log entry not four

---

build.sbt
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/IOUtils.scala
smrt-server-analysis-internal/src/test/scala/IOUtilsSpec.scala

I came across this TODO while reading some of the internal code. Added a test to show it works as expected. Previously, the test had an example with a port but didn't assert it parsed correctly. Now it does.
```bash
sbt "smrt-server-analysis-internal/testOnly IOUtilsSpec"
```
The change also allowed for dropping a dependency.

Added port parsing

---

project/plugins.sbt

This adds code coverage support via [scoverage](https://github.com/scoverage/sbt-scoverage). Handy to gauge if tests are lacking or if code is unused by known integration tests. Also means we can add [coveralls.io](https://coveralls.io/) for free, including GH hooks.
```bash
sbt clean coverage test coverageReport
```
Then lookup the HTML report in the respective `target/` subdir. e.g. `smrtflow/smrt-server-analysis-internal/target/scala-2.11/scoverage-report/index.html`
And here is a class that I added a test for in #77

Added scoverage plugin

---

project/plugins.sbt

This adds the [Coveralls.io](https://coveralls.io/github/PacificBiosciences/smrtflow) plugin so that `smrtflow` code coverage reports can be hosted. The `scoverage` docs [note how to setup coveralls.](https://github.com/scoverage/sbt-coveralls).
Right now, I'm exporting the coveralls key manually. If we add this to CI we'll need to add the secret.
```bash
export COVERALLS_REPO_TOKEN=...
```
Then you run coverage #78, `coverageAggregate` and `coveralls`.
```bash
sbt sbt clean coverage test coverageAggregate coveralls
```
Results are posted in the UI. GH hooks can also be added to post in PR threads.
And it shows per-file break downs of conditionals.

Coveralls (Code Coverage SaaS)

---

smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/SecondaryInternalAnalysis.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/appcomponents/SecondaryAnalysisApp.scala
smrt-server-base/src/main/scala/com/pacbio/common/app/BaseSmrtServerApp.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/app/SmrtLinkApp.scala
smrt-server-logging/src/main/scala/com/pacbio/logging/LoggerOptions.scala

Fixes #90
CC @skinner @mpkocher 
Switched default `App` use of logging to have `--debug` specified. There is no need to manually add the flag. You can still use the `--logfile` and other logging params. 
Tests pass
```
sbt clean test
```
Running the server by hand with no extra args now defaults to debug as expected.
```
sbt smrt-server-analysis/assembly
java -jar smrt-server-analysis/target/scala-2.11/smrt-server-analysis*.jar
2016-05-25  INFO [main] c.p.s.s.a.SecondaryAnalysisServer$ - Starting App
2016-05-25  INFO [main] c.p.s.s.a.SecondaryAnalysisServer$ - Java Version: 1.8.0_92
2016-05-25  INFO [main] c.p.s.s.a.SecondaryAnalysisServer$ - Java Home: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre
2016-05-25  INFO [main] c.p.s.s.a.SecondaryAnalysisServer$ - Java …
```

Default --debug for App classes

---

smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/services/LimsResolverService.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/services/ReferenceSetResolverService.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/services/SmrtLinkResourceService.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/services/jobtypes/ConditionJobType.scala
smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/tempbase/package.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/DataSetImportService.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/PipelineTemplateViewRulesService.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/ReportViewRulesService.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/ResolvedPipelineTemplateService.scala
smrt-server-base/src/main/scala/com/pacbio/common/models/JsonProtocols.scala
smrt-server-base/src/main/scala/com/pacbio/common/models/Models.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/AbstractFilesService.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/CleanupService.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/ConfigService.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/HealthService.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/LogService.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/ManifestService.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/StatusService.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/SubSystemComponentService.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/SubSystemResourceService.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/UserService.scala
smrt-server-base/src/test/scala/PacbioJsonProtocolSpec.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/DataSetService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobManagerService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/ProjectService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/RegistryService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/RunService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/SampleService.scala

CC @mpkocher look good?
In working on #89 I realized `None` is passed many times when `PacBioComponentManifest` is created for services. Only 4 or so uses pass an arg. Making `None` tidies up the code a fair bit and avoids needing to put an (often unnamed) arg of `None`.
```scala
case class PacBioComponentManifest(id: String, name: String, version: String, description: String, dependencies: Option[Seq[PacBioComponent]])
```
```scala
case class PacBioComponentManifest(id: String, name: String, version: String, description: String, dependencies: Option[Seq[PacBioComponent]] = None)
```
Which lets you do cleanup such as the following in over 20 spots in our codebase.
```scala
val manifest = PacBioComponentManifest(toServiceId("smrtlink_resource_resolver"),
"SMRT Link Resource Resolver", …
```

`None` as the default PacBioComponentManifest dependency arg

---

build.sbt
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/engine/CommonMessages.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/engine/actors/EngineManagerActor.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/engine/actors/EngineWorkerActor.scala

- "quick" jobs will run in quick workers if avail, or default to the standard workers (if avail)
- Not thrilled but trying to keep the changes to a minimum (want this up on SL beta)
- I have a better longer term solution

Enable running quick workers and standard workers to run jobs by type

---

smrt-server-base/src/main/scala/com/pacbio/common/actors/StatusServiceActor.scala

Fixes #84 
Loading property files in scala seems to rely on the same old (slightly) cumbersome Java `Properties` and `load` method. I updated our `buildVersion` method to do that.
```bash
sbt clean smrt-server-analysis/assembly smrt-server-analysis/run
curl http://localhost:8070/status
{
"uuid": "f18647c4-591a-462c-8867-96fc28c26505",
"version": "af4a30e670a76f3a38e2fdc420455c830e0dc479",
"id": "pacbio.smrtservices.smrtlink_analysis",
"uptime": 4388,
"message": "Services have been up for 4.388 seconds.",
"user": "jfalkner"
}
```
I couldn't find a convenient Scala way to walk the ClassLoader tree, look for `properties` files with a given name and give the first one back as a map. I may cook this up for fun.

Load version from existing version.properties

---

build.sbt
smrt-server-base/src/main/scala/com/pacbio/common/actors/StatusServiceActor.scala

CC @mpkocher 
Fixes #84 and followup to #107 
Conversion to use a common name + abbreviated hash in the version string. Now version strings appear similar to `0.1.2-f1cdc23` where the values are VERSION + SHA1, when VERSION has "SNAPSHOT" trimmed and the SHA1 is truncated to 7 chars.
Full version and SHA are available in the `verrsion.properties` file. 
Example showing how to see this version string.
```
sbt clean smrt-server-analysis/assembly smrt-server-analysis/run
curl http://localhost:8070/status
{
"uuid": "c7faa168-6965-4932-86e8-eba51f1f2b12",
"version": "0.1.2-f1cdc23",
"id": "pacbio.smrtservices.smrtlink_analysis",
"uptime": 2593,
"message": "Services have been up for 2.593 seconds.",
"user": "jfalkner"
}
```

Short version format. e.g. "0.1.2-f1cdc23"

---

smrt-server-logging/README.md
smrt-server-logging/src/main/scala/com/pacbio/logging/LoggerConfig.scala
smrt-server-logging/src/main/scala/com/pacbio/logging/LoggerOptions.scala

CC @skinner @mpkocher 
Fixes #103
This PR updates the default logging behavior to match the [clarified expectations](https://github.com/PacificBiosciences/smrtflow/issues/103#issuecomment-222753670) here. The change also ends up reducing a chunk of the verbose Slick logging #103 since it hides DEBUG level messages. I also improved the code to persist logging config state since sometimes the `Configurator` timing appears to sometimes change. e.g. debugger vs command-line
[README.md docs](https://github.com/PacificBiosciences/smrtflow/blob/logger_debug_default/smrt-server-logging/README.md) are updated too.
Can test by running the analysis server.
```bash
sbt clean compile smrt-server-analysis/assembly
sbt smrt-server-analysis/run
...
[info] 2016-06-01  INFO …
```

Logger default level INFO and reduce Slick logging verbosity

---

scalastyle-config.xml
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/converters/FastaConverter.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/reports/Reports.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/SubSystemResourceService.scala
smrt-server-base/src/main/scala/com/pacbio/common/services/package.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/tools/SetupMockData.scala
smrt-server-link/src/main/scala/db/migration/V1__InitialSchema.scala

> WIP: not yet ready for merge.
Continues #95 and adds style checking for expected naming conventions. 
Adds naming style checks: Class, Object, Package, Method
Ignores a few easy-to-check items because it isn't clear from the style specs if this is needed. We can decide for our code base some other time.
- Enforce a single space before and after `+` symbols
- Enforce no whitespace at the end of lines

Scalastyle Checker: Part 2

---

.gitignore
stress.py

Import subreadset as part of the stress test.
Also, if the test referenceset had been imported with the original UUID, stress.py would run successfully, but if not, then then the dev_diagnostic pipeline would fail to run because it expected the original referenceset UUID.

import the original referenceset, import subreadset

---

smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala

@mpkocher alternatively, we could further split the task ID by '.' and take the last element, so 'mapping_stats', 'ccs_report', and so on

use task ID as report type ID

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/converters/FastaToGmapReferenceConverter.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/externaltools/CallGmapBuild.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/tools/FastaToGmapReferenceSet.scala

Mimicking the behavior of fasta-to-reference

fasta-to-gmap-reference: copy input fasta to new location before creating indices

---

smrt-server-logging/src/main/scala/com/pacbio/logging/LoggerOptions.scala

CC @natechols @mpkocher @skinner 
Fixes #186 
@skinner Heads up that I changed `--logfile` to match `--log-file` in the python CLI params. This will mean that any deploy script that sets the file via `--logfile` will need to add the hyphen. Please confirm we're good to merge with this edit.
You can make/run this code similar to #111. 
```
sbt clean compile smrt-server-analysis/assembly
$ sbt "smrt-server-analysis/run --help"
...
[info] Running com.pacbio.secondary.smrtserver.appcomponents.SecondaryAnalysisServer --help
[info] Usage: ./app_with_logging [options]
[info] 
[info] This is an app that supports PacBio logging flags. 
[info]   -h | --help
[info]         Show Options and exit
[info]   --log2stdout
[info]         If true, log output will be displayed to the console. Default is …
```

Match Python CLI-style params

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/services/jobtypes/PbsmrtpipeServiceJobType.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala
smrt-server-analysis/src/test/scala/JobExecutorSpecBase.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/Models.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/SmrtLinkJsonProtocols.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/jobtypes/ValidateImportDataSetUtils.scala
smrt-server-link/src/test/scala/JobExecutorSpec.scala

The change to ValidateImportDataSetUtils.scala is a bit hacky - I was trying to avoid changing anything relating to the database

workaround for ID vs. UUID inconsistency in entry point JSON

---

smrt-server-database/README.md
smrt-server-database/src/main/scala/com/pacbio/database/Database.scala
smrt-server-database/src/main/scala/com/pacbio/database/DatabaseListener.scala
smrt-server-database/src/main/scala/com/pacbio/database/LoggingListener.scala
smrt-server-database/src/main/scala/com/pacbio/database/ProfilingListener.scala

> WIP: need to flesh out docs and improve this description. Good to merge this PR when CircleCI is green. This code doesn't fix `stress.py`, rather it just shows how to see what DB calls need un-nesting. `unwrap_nested_db_run_usage` is the branch with the example fixes.
CC @mpkocher @skinner 
This includes some DB debugging improvements that I used to help clarify the nested query issue that appears to be the root cause of #161.
Running this branch should trigger the new guard that shows a more informative error such as the following, which notes that `insertDataStoreByJob` at `JobsDao.scala:505` timed out probably due to nested queries.
```
[info] 2016-06-22  ERROR[ForkJoinPool-2-worker-1] c.p.d.LoggingListener - [PacBio:Database]  RDMS timeout for …
```

Guard for nested queries

---

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/testkit/Models.scala
smrt-server-analysis/src/test/resources/testkit/testkit_cfg.json
smrt-server-analysis/src/test/scala/TestkitSpec.scala

This is only the first step, but I'd like to get some quick feedback before using this.  Currently the JSON spec looks something like this:
```
{
"jobName": "test_job",
"workflowXml": null,
"entryPoints": [{
"entryId": "eid_subread",
"path": "/path/to/subreadset.xml"
}, {
"entryId": "eid_ref_dataset",
"path": "/path/to/referenceset.xml"
}],
"description": "simple test config",
"jobType": "pbsmrtpipe",
"outputDir": null,
"presetXml": "preset.xml",
"reportTests": [{
"reportId": "example_report",
"rules": [{
"attrId": "mapped_reads_n",
"op": "gt",
"value": 100
}, {
"attrId": "concordance",
"op": "ge",
"value": 0.85
}, {
"attrId": "instrument",
"value": "54006"
}]
}],
"pipelineId": "pbsmrtpipe.pipelines.sa3_sat"
}
```
In the old testkit code, the report attribute rules are specified like …

models for new testkit config

---

smrt-server-database/README.md
smrt-server-database/src/main/scala/com/pacbio/database/ProfilingListener.scala

CC @skinner 
Fixes #149
Some improvements to the `ProfilingListener` so that approximate timing metrics exist for the time it takes Slick + RDBMS (SQLite currently) to execute a `DBIOAction`. [README.md](https://github.com/PacificBiosciences/smrtflow/blob/db_usage_timing/smrt-server-database/README.md#query-timing) updates have the example, but now upon JVM exit both usage and timing metrics are dumped.
```
Code,Sum,Avg,Min,Max,Usage
c.p.s.s.a.DataSetStore$class.getSubreadDataSets(JobsDao.scala:713), 2157, 134, 108, 188, 16
c.p.s.s.a.JobDataStore$class.getJobsByTypeId(JobsDao.scala:382), 1350, 32, 0, 99, 42
c.p.s.s.a.DataSetStore$class.getAlignmentDataSets(JobsDao.scala:796), 1016, 101, 82, 131, 10
c.p.s.s.a.JobDataStore$class.getJobs(JobsDao.scala:379), 385, 128, 92, 191, 3 …
```

Slick + RDBMS timing

---

smrt-server-database/src/main/scala/com/pacbio/database/Database.scala

CC @skinner 
Runs Flyway migrations in an eager fashion but otherwise keeps the same guard in place to make sure migrations have run before other `db.run` use occurs.
This is a followup to a discussion on Slack where @skinner noted that some timeouts were being observed while running `stress.py` because the first few `db.run` usages blocked on relative long-running migrations.

Eager Flyway migrations

---

smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDaoActor.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/database/TableModels.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/Converters.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/DataSetService.scala
smrt-server-link/src/main/scala/db/migration/V13__MoreDatasets.scala

I got a little more aggressive with refactoring this time since it was starting to get messy - including consolidating some code that Steve had tagged as redundant.
btw we should really stick to the canonical naming as widely as possible - it's confusing that we have `ConsensusRead` in some places, and `CCSread` in others (and even `CCSSubread` before I replaced it).

Dataset services for ContigSet, ConsensusAlignmentSet

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/constants/FileTypes.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/externaltools/PbReports.scala
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/reports/DataSetReports.scala

It's gross but it works.  Here's how I test it using PacBioTestData after calling `sbt smrt-server-analysis/run`:
```
./smrt-server-analysis/target/pack/bin/pbservice import-dataset --host localhost --port 8070 `pbdata get subreads-sequel`
./smrt-server-analysis/target/pack/bin/pbservice import-dataset --host localhost --port 8070 `pbdata get subreads-xml`
```
The first SubreadSet includes an sts.xml and has pbreports reports run, the second does not.  I can easily turn this into an automated test using the new pbtestkit-service-runner - not sure where this should live though.

Dataset report fixes

---

smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/engine/actors/EngineManagerActor.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDaoActor.scala

Before this change, I was seeing 12 to 50 of `Ask timed out` errors when I ran `pbtestkit-service-multirunner service-test-tiny-jobs.txt` with a copy of the smrtlink-beta database (on NFS).
With this change, I see two `Ask timed out` errors (I've run one complete test run so far).
The periodic GetSystemJobSummary tick would query for all the engine jobs and all the datastore files (two of the larger tables in our DB).  If a separate query was queued behind those queries, it could run into the ask timeout.
AFAIK most developers are working on an SSD and/or with a small database, and you wouldn't hit those timeouts in that case.
We should increase the timeouts as well; I'll make a separate PR for that.

disable system job summary tick

---

smrt-server-database/src/main/scala/com/pacbio/database/Database.scala

Quick fix to incorrect `commit()` use. This should have previously always failed with the exception logged then ignored.
The [JavaDocs note](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#commit())
> Makes all changes made since the previous commit/rollback permanent and releases any database locks currently held by this Connection object. This method should be used only when auto-commit mode has been disabled.
So the old cleanup wasn't helpful. In the case of auto-commit (default, I think) this wouldn't work. In the case of no auto-commit, the transaction was not manually committed for some reason. It is unclear if it is correct to assume it should be committed.

Remove commit() cleanup

---

smrt-common-models/src/main/java/com/pacificbiosciences/pacbiorightsandroles/RnR.java
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/app/SmrtLinkApp.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/database/DatabaseSampleDao.scala

The routes were using an InMemoryDao like the unit tests; this change is to switch to the DB instead. For bugzilla 31624. Also a change to remove a curly unicode quote from a comment which tripped up my build on Mac.

Switch sample service to use DB

---

smrt-server-lims/build.sbt

Enables the current `smrt-lims` server to import subreadset.xml files. After switching to use assembly, the eclipse persistence API was dropped, which caused errors when parsing XML. It now works. Tested manually.

Don't discard eclipse API. Needed for subreadset.xml parsing

---

smrt-server-logging/src/main/scala/com/pacbio/logging/LoggerOptions.scala

CC @skinner @mpkocher 
Fixed use of the `--log-file` flag. What happened is that a helper method that would auto-set `--debug` if no file or debug was set got out of sync with a change that did `s/--logfile/--log-file`.
Probably should have been covered by a test. Can file a ticket for that if desired later. This should fix it.
```
$ sbt "smrt-server-analysis/run --log-file /tmp/foo.log"
...
cat /tmp/foo.log
$ sbt "smrt-server-analysis/run --log-file foo.log"
...
cat smrt-server-analysis/foo.log
```

Fixed --log-file flag

---

smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDaoActor.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/Models.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/SmrtLinkJsonProtocols.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/ProjectService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/tools/SetupMockData.scala
smrt-server-link/src/test/scala/ProjectSpec.scala

The original API had separate endpoints for changing the lists of users and datasets in a project.  But dbarreto objected on the grounds that the project page had one save button, and if multiple requests were required to save a project, it was awkward on the client to track the success/failure of partial project saves.  So this change makes it so that saving a project is a single request with a body that contains the project member/dataset lists.

Project api changes

---

extras/wso2/create_roles.sh

If you think this is too hacky, then we don't have to merge it.  It's pretty quick-and-dirty.  But it does get us off the ground for this sprint, in terms of automatically creating roles.
I've tested it against my local wso2 AM installation, but bihourly is down at the moment, so I haven't tried it there.

add script to create wso2 roles with curl

---

extras/wso2/smrtlink_swagger.json
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobManagerService.scala

Some fixes to API manager issues from yesterday and today.  The analysis scope name changes fixes the job creation failures from yesterday, and the x-auth-type and content-disposition change fix the download failures.

Api manager fixes

---

smrt-server-analysis-internal/src/main/scala/com/pacbio/secondaryinternal/client/InternalAnalysisServiceClient.scala
smrt-server-analysis-internal/src/test/scala/ConditionalJobSpec.scala

CC @evolvedmicrobe, @mpkocher 
Fixes [ITG-159](https://jira.pacificbiosciences.com/browse/ITG-159). See the JIRA ticket, but in short a list of jobs was given where one of the jobs lacked the expected `SubreadSet`. The error message was along the lines of the following.
```
java.lang.Exception: Failed resolve Entry Point type PacBio.DataSet.SubreadSet
```
This PR will change it to be this.
```
Failed resolve A_30622's Entry Point of type PacBio.DataSet.SubreadSet for jobId 30622 at smrtlink-beta:8081
```

Better error message for conditional jobs without expected data

---

extras/pbbundler/smrtlink_services_ui/bin/apply-config

Now that the RemoteUserStoreManagerService API exists alongside the SMRTLink API, the config shouldn't include the `SMRTLink/1.0.0` prefix anymore.
This smrtflow change goes along with this client-side change: http://swarm/reviews/187716
If/when this PR gets merged, I'll update the smrtflow ini and submit that client-side change at the same time.

remove SMRTLink/1.0.0 prefix (there are other prefixes now)

---

extras/pbbundler/smrtlink_services_ui/bin/start
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/AmClient.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/ApiManagerAccessLayer.scala

This sets the backend port and the swagger at services start time, fixing SL-431 and relieving us from having to update the wso2 zip when we add new endpoints to the swagger.

[SL-431] set backend port

---

smrt-server-base/src/main/scala/com/pacbio/common/app/BaseSmrtServerApp.scala

- commented code related to logging and cleanup from CoreProvider trait
pa-xfer inherits from CoreProviders, logging related classes, due to singleton error would prevent pa-xfer from starting. seq-780.

Remove log

---

smrt-server-link/src/main/scala/db/migration/SlickMigration.scala
smrt-server-link/src/main/scala/db/migration/V17__AddIndexToEngineJobs.scala
smrt-server-link/src/main/scala/db/migration/V23__JobEventsIndex.scala
smrt-server-link/src/main/scala/db/migration/V8__JobUser.scala
smrt-server-link/src/test/scala/DatabaseSpec.scala

We used to swallow migration exceptions in an Await.ready.  This changes the `ready` to a `result` so that exceptions propagate and get reported.  But that change means that the V17 migration that was generating an exception would stop the migration process.
So this also changes the V17 migration to only include the changes that were successfully made, before it hit the exception.  Changing a past migration that has been applied on various instances is something I would ordinarily say was a no-no, but I think this is a special case.  The effect of the new, shorter V17 is the same as the effect of the old V17; only the statement that resulted in an error (and the subsequent statements, which weren't getting run) have been removed.
It also re-adds the index on job_events.

[SL-619] Report migration errors and recreate job_events index

---

makefile
smrt-analysis/src/main/scala/com/pacbio/secondary/analysis/jobs/JobExecutor.scala
smrt-server-analysis/src/main/resources/application.conf
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/client/ServiceAccessLayer.scala
smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/tools/PbService.scala
smrt-server-database/src/main/scala/com/pacbio/database/Database.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/EulaService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobManagerService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/JobsBaseMicroService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/SmrtLinkBaseMicroService.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/jobtypes/ValidateImportDataSetUtils.scala

Without this change, the methods to get the next runnable job leave the next runnable in the queue while they search for the job entry in the database.  While that database operation is happening, another worker can ask for a runnable job and get the same job, resulting the in the same job getting run by multiple workers.  And we do see that happen - in the week that 4.0 has been running on alpha, at least two jobs ([5d9fbc6f-0254-4e22-bbd6-c9f6cec64801](http://smrtlink-alpha:8081/secondary-analysis/job-manager/jobs/2144/events) and [29e54346-3764-401e-af5d-433bda54a276](http://smrtlink-alpha:8081/secondary-analysis/job-manager/jobs/1837/events)) have been run twice.
This changes the job removal to happen before the database lookup.  With that change, I no longer see jobs getting run …

[SL-620] Fix runnablejob race and bump timeouts

---

extras/pbbundler/smrtlink_services_ui/bin/start

This is what let JGI smrtlink start up, with their setup that disabled overcommit and had a virtual memory ulimit.

[SL-637] set heap size for API manager client

---

smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/Models.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/models/SmrtLinkJsonProtocols.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/services/ProjectService.scala
smrt-server-link/src/test/scala/ProjectSpec.scala

We had an extra level of nesting in project member info, but the wso2 changes made it unnecessary because the backend only deals in logins now.  This removes that level of nesting; I'd like to get it in to unblock frontend work on SL-20, and it's fairly contained to project-member-related code, so it shouldn't create merge issues.

remove extra nesting from project user

---

README.md

By default, psql connects to a database with the same name as your username.  If there isn't a database with that name, you get the `psql: FATAL:  database "mskinner" does not exist` error.  You can avoid the error by specifying a db name on the psql command line.

specify db name in psql examples

---

smrt-server-analysis/src/main/resources/smrtlink_swagger.json

added endpoint definitions for:
/secondary-analysis/datasets/alignments/{dataset-id}
/secondary-analysis/datasets/hdfsubreads/{dataset-id}
/secondary-analysis/datasets/subreads/{dataset-id}
/secondary-analysis/datasets/barcodes/{dataset-id}
/secondary-analysis/datasets/contigs/{dataset-id}
/secondary-analysis/datasets/references/{dataset-id}
/secondary-analysis/datasets/ccsalignments/{dataset-id} 
/secondary-analysis/datasets/gmapreferences/{dataset-id}

add {Dataset}Details defintions to smrtlink_swagger.json
